project_name: amdecrypt
version: 1

before:
  hooks:
    - go mod tidy

builds:
  - id: amdecrypt
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -tags=netgo
    ldflags:
      - -X main.Version={{ .Version }}
      - -X main.Commit={{ .Commit }}
      - -X main.CommitDate={{ .CommitDate }}
      - -X main.TreeState={{ .TreeState }}

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: glomatico
    name: amdecrypt
